// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMq74ZISmmHiGXQM-6IZtgF4Ip9YXlklc',
    appId: '1:923556785147:web:937c5b2242fdba41eeb95e',
    messagingSenderId: '923556785147',
    projectId: 'myj-firebase',
    authDomain: 'myj-firebase.firebaseapp.com',
    storageBucket: 'myj-firebase.appspot.com',
    measurementId: 'G-MB7NSCSGQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMq74ZISmmHiGXQM-6IZtgF4Ip9YXlklc',
    appId: '1:923556785147:android:3dacd6df1ed1737deeb95e',
    messagingSenderId: '923556785147',
    projectId: 'myj-firebase',
    storageBucket: 'myj-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMq74ZISmmHiGXQM-6IZtgF4Ip9YXlklc',
    appId: '1:923556785147:ios:ff9c85e8bb38b948eeb95e',
    messagingSenderId: '923556785147',
    projectId: 'myj-firebase',
    storageBucket: 'myj-firebase.appspot.com',
    iosClientId:
        '923556785147-rn7mg06mh736njjlop6sihujk8hn46du.apps.googleusercontent.com',
    iosBundleId: 'com.tpyccc.elderly-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMq74ZISmmHiGXQM-6IZtgF4Ip9YXlklc',
    appId: '1:923556785147:ios:ff9c85e8bb38b948eeb95e',
    messagingSenderId: '923556785147',
    projectId: 'myj-firebase',
    storageBucket: 'myj-firebase.appspot.com',
    iosClientId:
        '923556785147-rn7mg06mh736njjlop6sihujk8hn46du.apps.googleusercontent.com',
    iosBundleId: 'com.tpyccc.elderly-app',
  );
}
